# Generated by Django 3.2.3 on 2021-05-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_teams_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='designation',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
