# Generated by Django 3.2.3 on 2021-05-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_teams_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='photo',
            field=models.ImageField(default=None, upload_to='photos/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
