# Generated by Django 3.2.3 on 2021-05-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_teams_facebook_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='twitter_link',
            field=models.URLField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
