# Generated by Django 3.2.3 on 2021-05-23 15:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_teams_google_plus_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
