# Generated by Django 3.2.3 on 2021-05-23 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_teams_created_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teams',
            options={'verbose_name': 'Team'},
        ),
    ]
