# Generated by Django 3.2.3 on 2021-05-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_car_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='condition',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
