# Generated by Django 3.2.3 on 2021-05-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_car_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
