# Generated by Django 3.2.3 on 2021-05-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_car_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(default=None, max_length=700),
            preserve_default=False,
        ),
    ]
