# Generated by Django 3.2.3 on 2021-05-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_car_car_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_photo_1',
            field=models.ImageField(default=None, upload_to='photos/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
