# Generated by Django 3.2.3 on 2021-05-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0015_auto_20210527_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='engine',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
