# Generated by Django 3.2.3 on 2021-05-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0020_alter_car_doors'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='passengers',
            field=models.IntegerField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
