# Generated by Django 3.2.3 on 2021-05-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0025_auto_20210527_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='number_of_owners',
            field=models.CharField(default=None, max_length=120),
            preserve_default=False,
        ),
    ]
