# Generated by Django 3.2.3 on 2021-05-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0030_alter_car_vin_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='doors',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='passengers',
            field=models.PositiveIntegerField(),
        ),
    ]
