# Generated by Django 3.2.3 on 2021-06-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0031_auto_20210528_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='miles',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
